config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'pages#welcome'
  get '/home' => 'cities#index'
  
  # Session routes;
  get '/login' => 'session#new'
  # login form
  # form submits to here, does authentication, 
  post '/login' => 'session#create'

  delete '/login' => 'session#destroy'
  #logout
  
  resources :users
  resources :startups
  resources :cities
  resources :favourites
  resources :coworking_spaces
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord

# has_many :coworking_spaces
has_many :startups

# belongs_to_many :countries

# has_and_belongs_to_many :favourites

end

app/models/coworking_space.rb
class CoworkingSpace < ApplicationRecord

    has_many :startup

    belongs_to :city, optional: true
end

app/models/favourite.rb
class Favourite < ApplicationRecord
    belongs_to :users, optional: true
    # has_and_belongs_to_many :cities
    # has_and_belongs_to_many :startups
end

app/models/startup.rb
class Startup < ApplicationRecord

belongs_to :city, optional: true

end

app/models/user.rb
class User < ApplicationRecord

    has_many :favourites

    # Use brcypt gem
    has_secure_password

    # form validation
    validates :name, length: { minimum: 2 }

    validates :email, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :fetch_user

def fetch_user

    #check whether the user_id in the session is the iD of a real user in DB.
    if session[:user_id].present?
        @current_user = User.find_by id: session[:user_id]
    end #session checker

    # if nil from above query, delete session because user_id is stale()
    session[:user_id] = nil unless @current_user.present?
    end # fetch_user

    def check_if_logged_in

    #If current browser user not logged in, method redirects to login page;
        redirect_to login_path unless @current_user.present?
    end 


end # applicationController

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def new
  end

  def create
  end

  def index
    @cities = Startup.all.group_by(&:city)
  end

  def show
    @city = City.find params[:id]
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/coworking_spaces_controller.rb
class CoworkingSpacesController < ApplicationController
  
  before_action :check_if_logged_in, except: [ :index, :show]

  def new
    @coworking_space = CoworkingSpace.new #new empty object in memory to give to form_for.
  end

  def create

    # Handle upload, if file was uploaded
    if params[:file].present?
      # actually forward uploaded file on to Cloudinary server
      response = Cloudinary::Uploader.upload params[:file]
      @coworking_space.image = response['public_id']      
      @coworking_space.save
    end

    CoworkingSpace.create coworking_space_params #
    redirect_to coworking_spaces_path
  end

  def index
    @coworking_spaces = CoworkingSpace.all
  end

  def show
    @coworking_space = CoworkingSpace.find params[:id]
  end

  def edit
    @coworking_space = CoworkingSpace.find params[:id] 
  end

  def update
    @coworking_space = CoworkingSpace.find params[:id]

    # Update the record with strong params:
    @coworking_space.update coworking_space_params

    # Redirect to show page.
    redirect_to( coworking_spaces_path(params[:id]) )

  end

  def destroy
    CoworkingSpace.destroy params[:id]
    redirect_to coworking_spaces_path
  end


  private 
  def coworking_space_params
    params.require( :coworking_space).permit(:name, :image, :description, :reviews, :companies)
  end

end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def new
  end

  def create
  end

  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    before_action :check_if_logged_in, only: [ :home ]

    def welcome
    end

    def home
        # check_if_logged_in
    end

    private

end # Pages_controller

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end # new

  def create
    user = User.find_by email: params[:email]

    if user.present? && user.authenticate( params[:password])
    
      session[:user_id] = user.id
      
      redirect_to home_path

    else 
      flash[:error] = 'Invalid email or password'
      redirect_to login_path

  end #login check
end # create

  def destroy
    session[:user_id] = nil #Logs out the user.
    redirect_to login_path
  end

end # session controller

app/controllers/startups_controller.rb
class StartupsController < ApplicationController
  before_action :check_if_logged_in, except: [ :index, :show]
  
  def new
    @startup = Startup.new #new empty object in memory to give to form_for.
  end

  def create
    
    @startup = Startup.create startup_params #
    # Handle upload, if file was uploaded
    if params[:file].present?
      # actually forward uploaded file on to Cloudinary server
      response = Cloudinary::Uploader.upload params[:file]
      @startup.image = response['public_id']      
      @startup.save
    end

    redirect_to startups_path
  end

  def index
    @startups = Startup.all
  end

  def show
    @startup = Startup.find params[:id]
  end

  def edit
    @startup = Startup.find params[:id] 
  end

  def update
    @startup = Startup.find params[:id]

    # Update the record with strong params:
    @startup.update startup_params

    # Redirect to show page.
    redirect_to( startup_path(params[:id]) )

  end

  def destroy
    Startup.destroy params[:id]
    redirect_to startups_path
  end


  private 
  def startup_params
    params.require( :startup).permit(:name, :description, :valuation, :funding, :status, :employees, :image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_if_logged_in, except: [ :new, :show]

  def index
    @users = User.all
  end

  def new
    @user = User.new # b/c the form_form helper needs @user.
  end

  def create

    @user = User.create user_params

    # Handle upload, if file was uploaded
    if params[:file].present?
      # actually forward uploaded file on to Cloudinary server
      response = Cloudinary::Uploader.upload params[:file]
      @user.image = response['public_id']      
      @user.save
    end

    # @user.user_id = @current_user.id
    #@user.save
    
    if @user.persisted?
      #check whether the above create successful
      session[:user_id] = @user.id  #log in the newly created account
      redirect_to root_path

    else
      render :new
    end
  end #create

  def show
    @user = User.find params[:id]
  end 

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit( :name, :email, :password, :password_confirmation, :image, :bio, :linkedin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/coworking_spaces_helper.rb
module CoworkingSpacesHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/startups_helper.rb
module StartupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/edit.html.erb
<h1>Cities#edit</h1>
<p>Find me in app/views/cities/edit.html.erb</p>

app/views/cities/index.html.erb
<div class="container">
    <% @cities.each do |city, startups| %>
        <div class="card">
            <%= link_to city_path(city.id) do %>
                <%= image_tag(city.image1, class: 'cities') %>
                <br>
                <strong><%= city.name %></strong>
                <p>Startups:</p>
                <ul class="icons">
                <% startups.each do |s| %>
                    <li> 
                    <%= link_to startup_path(s.id) do %>
                        <%= image_tag(s.image, class: 'icons') %>
                    </li>
                    <% end%>
                <% end %>
                </ul>
            <% end %> 
        </div>
    <% end %> 
    </div> 

app/views/cities/new.html.erb
<h1>Cities#new</h1>
<p>Find me in app/views/cities/new.html.erb</p>

app/views/cities/show.html.erb
<h2><%= @city.name %></h2>

    <%= image_tag @city.image1, alt: @city.name, class: 'cities' %>

<p>
    <strong>Nomadlist Rank:</strong> <%= @city.rank %>
</p>

<p>
    <strong>Mercer 2019 quality of living survey score:</strong> <%= @city.mercer %>
</p>

<p> 
    <strong>📡Internet:</strong>
    <%= @city.internet_speed %>
</p>

    <%= image_tag @city.image2, alt: @city.name, class: 'cities' %>

<p></p>

app/views/cities/update.html.erb
<h1>Cities#update</h1>
<p>Find me in app/views/cities/update.html.erb</p>

app/views/coworking_spaces/_form.html.erb
<%= form_for @coworking_space, html: {multipart: true} do |f| %>

  <%= f.label :name %><br>
  <%= f.text_field :name %>
  <br>
  
  <%= f.label :image, 'Image URL' %>
  <%= f.cl_image_upload :image %>
  <br>

  <%= f.label :description %><br>
  <%= f.text_field :description %>
  <br>

  <%= f.label :reviews %><br>
  <%= f.text_field :reviews %>
  <br>

  <%= f.label :companies %><br>
  <%= f.text_field :companies %>
  <br>
  <br>
  
  <%= f.submit %>

<% end %>

app/views/coworking_spaces/edit.html.erb
<h2> 
    Edit <%= @coworking_space.name %>
</h2>

<%= render partial: 'form' %>

app/views/coworking_spaces/index.html.erb
<h2> Best coworking spaces for digital nomads </h2>

<div class="container">
    <% @coworking_spaces.each do |c| %>
        <div class="card">
            <%= link_to coworking_space_path(c.id) do %>
                <%= image_tag(c.image, class: 'coworking_spaces') %>
                <br>
                <strong><%= c.name %></strong>
                <li><%= c.description %></li>
            <% end %> 
        </div>
    <% end %> 
    </div> 

app/views/coworking_spaces/new.html.erb
<h2>Add new coworking space</h2>

<%= render partial: 'form' %>

app/views/coworking_spaces/show.html.erb
<%= link_to 'Edit Coworking Space', edit_coworking_space_path(@coworking_space.id) %>
|
<%= link_to 'Delete coworking space', coworking_space_path(@coworking_space.id), method: 'delete' %>

<h2> <%= @coworking_space.name %> </h2>
<%= cl_image_tag @coworking_space.image, class: 'coworking_spaces', alt: @coworking_space.name %>

<table style="width:70%">
  <tr>
    <td> <strong>Coworking space description:</strong> </td>
    <td><%= @coworking_space.description %></td>
  </tr>
  <tr>
    <td><strong>Reviews:</strong> </td>
    <td><%= @coworking_space.reviews %></td>
  </tr>
  <tr>
    <td><strong>Companies:</strong></td>
    <td><%= @coworking_space.companies %></td>
  </tr>
  <tr>
    <td><strong>Find out more</strong></td>
    <td><a href="<%= @coworking_space.website_url%>"><%= @coworking_space.name %> Website</td>
  </tr>
</table>

app/views/favourites/create.html.erb
<h1>Favourites#create</h1>
<p>Find me in app/views/favourites/create.html.erb</p>

app/views/favourites/destroy.html.erb
<h1>Favourites#destroy</h1>
<p>Find me in app/views/favourites/destroy.html.erb</p>

app/views/favourites/edit.html.erb
<h1>Favourites#edit</h1>
<p>Find me in app/views/favourites/edit.html.erb</p>

app/views/favourites/index.html.erb
<h1>Favourites#index</h1>
<p>Find me in app/views/favourites/index.html.erb</p>

app/views/favourites/new.html.erb
<h1>Favourites#new</h1>
<p>Find me in app/views/favourites/new.html.erb</p>

app/views/favourites/show.html.erb
<h1>Favourites#show</h1>
<p>Find me in app/views/favourites/show.html.erb</p>

app/views/favourites/update.html.erb
<h1>Favourites#update</h1>
<p>Find me in app/views/favourites/update.html.erb</p>

app/views/session/create.html.erb
<h1>Sessions#create</h1>
<p>Find me in app/views/sessions/create.html.erb</p>

app/views/session/destroy.html.erb
<h1>Sessions#destroy</h1>
<p>Find me in app/views/sessions/destroy.html.erb</p>

app/views/session/new.html.erb
<h2>Login </h2>

<% if flash[:error] %>
    <!-- print out any error messages from the controller -->
    <br>
    <strong>
        <%= flash[:error] %>
    </strong>
    <br>
    <br>
<% end %>

<!-- we're not interacting with a model object, so we don't use 'form_for @obj  -->
<%= form_tag login_path do %>

    <%= label_tag :email %>
    <%= email_field_tag :email %>
     <br>
    
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <br>
    <%= submit_tag 'Login' %>

<% end%>

app/views/startups/_form.html.erb
<%= form_for @startup, html: {multipart: true} do |f| %>

  <%= f.label :name %><br>
  <%= f.text_field :name %>
  <br>

  <%= f.label :description %><br>
  <%= f.text_field :description %>
  <br>

  <%= f.label :valuation %><br>
  <%= f.text_field :valuation %>
  <br>

  <%= f.label :funding %><br>
  <%= f.text_field :funding %>
  <br>

  <%= f.label :status %><br>
  <%= f.text_field :status %>
  <br>

  <%= f.label :employees %><br>
  <%= f.text_field :employees %>
  <br>
  
  <%= f.label :image, 'Image URL' %><br>
  <%= f.cl_image_upload :image %>


  <%= f.submit %>

<% end %>

app/views/startups/edit.html.erb
<h2> 
    Edit <%= @startup.name %>
</h2>

<%= render partial: 'form' %>

app/views/startups/index.html.erb
<h2> List of startups in NomadList Cities </h2>

<div class="container">
    <% @startups.each do |s| %>
        <div class="card">
            <%= link_to startup_path(s.id) do %>
                <%= cl_image_tag(s.image, class: 'startups') %><br>
                <strong><%= s.name %></strong>
                <li><%= s.description %></li>
            <% end %> 
        </div>
    <% end %> 
    </div> 

app/views/startups/new.html.erb
<div class="wrapper">

    <h2>Add new startup</h2>

    <%= render partial: 'form' %>

</div>

app/views/startups/show.html.erb
<%= link_to 'Edit Startup', edit_startup_path(@startup.id) %>
|
<%= link_to 'Delete Startup', startup_path(@startup.id), method: 'delete' %>
<h2> <%= @startup.name %> </h2>

<%= cl_image_tag @startup.image, class: 'startups', alt: @startup.name %>

<table style="width:70%">
  <tr>
    <td> <strong>Startup description:</strong> </td>
    <td><%= @startup.description %></td>
  </tr>
  <tr>
    <td> <strong>Located in:</strong> </td>
    <td><%= @startup.city.name %></td>
  </tr>
  <tr>
    <td><strong>Valuation(USD):</strong> </td>
    <td><%= @startup.valuation %></td>
  </tr>
  <tr>
    <td><strong>Source of funding:</strong></td>
    <td><%= @startup.funding %></td>
  </tr>
  <tr>
    <td><strong>Status:</strong></td>
    <td><%= @startup.status %></td>
  </tr>
  <tr>
    <td><strong>Number of employees:</strong></td>
    <td><%= @startup.employees %></td>
  </tr>
  <tr>
    <td><strong>Find out more</strong></td>
    <td><a href="<%= @startup.website_url%>"><%= @startup.name %> Website</td>
  </tr>
</table>

app/views/startups/update.html.erb
<h1>Startups#update</h1>
<p>Find me in app/views/startups/update.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h2>
    <% @users.each do |u| %>
        <%= link_to u.name, user_path(u.id) %>
    <% end %>
</h2>gtgt

app/views/users/new.html.erb
<h2> Create an account</h2>

<% if @user.errors.full_messages.any? %>
    <ul>
    <% @user.errors.full_messages.each do |e|%>
    <li> <%= e %></li>
    <% end %>
    </ul>
    <% end %>


<%= form_for @user, html: {multipart: true} do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>

    <%= f.label :email %>
    <%= f.text_field :email %>
    <br>

    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <br>

    <%= f.label :image, 'Image URL' %>
    <!-- <%= f.text_field :image  %> -->
    <%= f.cl_image_upload :image %>

    <br>

    <%= f.label :bio %>
    <%= f.text_field :bio %>
    <br>

    <%= f.label :linkedin %>
    <%= f.text_field :linkedin %>
    <br>

    <%= f.submit 'Sign Up' %>

<% end %>

app/views/users/show.html.erb
    <h2>
        <%= @user.name %>
    </h2>

    <%= cl_image_tag @user.image %>