config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'pages#welcome'
  get '/home' => 'cities#index'
  
  # Session routes;
  get '/login' => 'session#new'
  # login form
  # form submits to here, does authentication, 
  post '/login' => 'session#create'

  delete '/login' => 'session#destroy'
  #logout
  
  resources :users
  resources :startups
  resources :cities
  resources :favourites
  resources :coworking_spaces
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord

# has_many :coworking_spaces
has_many :startups

# belongs_to_many :countries

# has_and_belongs_to_many :favourites

end

app/models/coworking_space.rb
class CoworkingSpace < ApplicationRecord

    has_many :startup

    belongs_to :city, optional: true
end

app/models/favourite.rb
class Favourite < ApplicationRecord
    belongs_to :users, optional: true
    # has_and_belongs_to_many :cities
    # has_and_belongs_to_many :startups
end

app/models/startup.rb
class Startup < ApplicationRecord

belongs_to :city, optional: true

end

app/models/user.rb
class User < ApplicationRecord

    has_many :favourites

    # Use brcypt gem
    has_secure_password

    # form validation
    validates :name, length: { minimum: 2 }

    validates :email, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :fetch_user

def fetch_user

    #check whether the user_id in the session is the iD of a real user in DB.
    if session[:user_id].present?
        @current_user = User.find_by id: session[:user_id]
    end #session checker

    # if nil from above query, delete session because user_id is stale()
    session[:user_id] = nil unless @current_user.present?
    end # fetch_user

    def check_if_logged_in

    #If current browser user not logged in, method redirects to login page;
        redirect_to login_path unless @current_user.present?
    end 


end # applicationController

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def new
  end

  def create
  end

  def index
    @cities = Startup.all.group_by(&:city)
  end

  def show
    @city = City.find params[:id]
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def new
  end

  def create
  end

  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    before_action :check_if_logged_in, only: [ :home ]

    def welcome
    end

    def home
        # check_if_logged_in
    end

    private

end # Pages_controller

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end # new

  def create
    user = User.find_by email: params[:email]

    if user.present? && user.authenticate( params[:password])
    
      session[:user_id] = user.id
      
      redirect_to home_path

    else 
      flash[:error] = 'Invalid email or password'
      redirect_to login_path

  end #login check
end # create

  def destroy
    session[:user_id] = nil #Logs out the user.
    redirect_to login_path
  end

end # session controller

app/controllers/startups_controller.rb
class StartupsController < ApplicationController
  before_action :check_if_logged_in, except: [ :index, :show]
  
  def new
    @startup = Startup.new #new empty object in memory to give to form_for.
  end

  def create
    
    @startup = Startup.create startup_params #
    # Handle upload, if file was uploaded
    if params[:file].present?
      # actually forward uploaded file on to Cloudinary server
      response = Cloudinary::Uploader.upload params[:file]
      @startup.image = response['public_id']      
      @startup.save
    end

    redirect_to startups_path
  end

  def index
    @startups = Startup.all
  end

  def show
    @startup = Startup.find params[:id]
  end

  def edit
    @startup = Startup.find params[:id] 
  end

  def update
    @startup = Startup.find params[:id]

    # Update the record with strong params:
    @startup.update startup_params

    # Redirect to show page.
    redirect_to( startup_path(params[:id]) )

  end

  def destroy
    Startup.destroy params[:id]
    redirect_to startups_path
  end


  private 
  def startup_params
    params.require( :startup).permit(:name, :description, :valuation, :funding, :status, :employees, :image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_if_logged_in, except: [ :new, :show]

  def index
    @users = User.all
  end

  def new
    @user = User.new # b/c the form_form helper needs @user.
  end

  def create

    @user = User.create user_params

    # Handle upload, if file was uploaded
    if params[:file].present?
      # actually forward uploaded file on to Cloudinary server
      response = Cloudinary::Uploader.upload params[:file]
      @user.image = response['public_id']      
      @user.save
    end

    # @user.user_id = @current_user.id
    #@user.save
    
    if @user.persisted?
      #check whether the above create successful
      session[:user_id] = @user.id  #log in the newly created account
      redirect_to root_path

    else
      render :new
    end
  end #create

  def show
    @user = User.find params[:id]
  end 

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit( :name, :email, :password, :password_confirmation, :image, :bio, :linkedin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/coworking_spaces_helper.rb
module CoworkingSpacesHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/startups_helper.rb
module StartupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nomadlist clone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    
    <%= cloudinary_js_config %>
  </head>

  <body>
  <h1> <%= link_to 'NomadList!', root_path %></h1>
  <header>
    <nav>
      <div class="navlink">
        <% if @current_user.present?%>
        Hello, <%= @current_user.name %> | <%= link_to 'Logout', login_path, method: 'delete'%>
      </div>

      <% else %>
      <div class="navlink">
        <%= link_to 'Login', login_path %></div>
      </div>
      <div class="navlink">
        <%= link_to 'Sign Up', new_user_path %> 
      </div>
    <% end %>
      <div class="navlink">
        <%= link_to 'NomadList Cities', cities_path %>
      </div>
      <div class="navlink">
        <%= link_to 'Startups', startups_path %>        
      </div>
      <div class="navlink">
        <%= link_to 'Coworking Spaces', coworking_spaces_path %>
      </div>
      <div class="navlink">
        <%= link_to 'Add startup', new_startup_path %>
      </div>
      <div class="navlink">
        <%= link_to 'Add coworking space', new_coworking_space_path %>
      </div>
    </nav>
  </header>
    <div class="wrapper">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/welcome.html.erb
<h2> Discover your next destination for remote working</h2>

<p>The world is increasingly moving towards remote working, so now's the time to take advantage of travel opportunities, once permitted.</p>

<p>We've put together some of the most popular cities, and some of the largest startups operating there. </p>
<p> Help us out by adding more startups and coworking spaces that you know of in the cities database.</p>